on:
  push:
    branch: [master]
    # tags:
    #   - "v*"
name: CI
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: goreleaser
        if: success()
        uses: docker://goreleaser/goreleaser:v1.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --config .github/goreleaser.yml
